import { BriefQuestion } from '@/types'

export const BRIEF_QUESTIONS: BriefQuestion[] = [
  {
    id: 'why',
    cat: 'Context',
    catNl: 'Context',
    text: 'Why does this brand need work right now? What changed, or what was never right?',
    placeholder: 'Take your time. The real reason is usually underneath the first answer.',
    textNl: 'Waarom heeft dit merk nu aandacht nodig? Wat is er veranderd, of wat klopte er nooit?',
    placeholderNl: 'Neem de tijd. De echte reden zit meestal onder het eerste antwoord.',
    clientText: 'What made you decide this was the right moment to work on your brand?',
    clientPlaceholder: 'There\'s no wrong answer. Start wherever feels natural.',
    clientTextNl: 'Wat deed je besluiten dat dit het juiste moment is om aan je merk te werken?',
    clientPlaceholderNl: 'Er is geen verkeerd antwoord. Begin waar het goed voelt.',
  },
  {
    id: 'belief',
    cat: 'Conviction',
    catNl: 'Overtuiging',
    text: 'Describe something this founder or company believes that most people in their category don\'t.',
    placeholder: 'Not a value. A specific, arguable belief.',
    textNl: 'Beschrijf iets wat deze oprichter of dit bedrijf gelooft wat de meeste mensen in hun categorie niet geloven.',
    placeholderNl: 'Geen waarde. Een specifieke, verdedigbare overtuiging.',
    clientText: 'What does your company believe that most others in your space wouldn\'t say out loud?',
    clientPlaceholder: 'The thing you\'d defend even if it cost you some customers.',
    clientTextNl: 'Wat gelooft jouw bedrijf dat de meeste anderen in jouw sector niet hardop zouden zeggen?',
    clientPlaceholderNl: 'Het ding dat je zou verdedigen, ook als het je klanten kost.',
  },
  {
    id: 'decision',
    cat: 'Character',
    catNl: 'Karakter',
    text: 'Describe a decision this company made that nobody outside would have made the same way.',
    placeholder: 'A real moment. Not a policy.',
    textNl: 'Beschrijf een beslissing die dit bedrijf nam die niemand buiten het bedrijf op dezelfde manier zou hebben genomen.',
    placeholderNl: 'Een echt moment. Geen beleid.',
    clientText: 'Tell us about a decision you made that surprised people — or that only made sense if you knew what you stood for.',
    clientPlaceholder: 'A real moment, not a principle.',
    clientTextNl: 'Vertel over een beslissing die mensen verraste — of die alleen klopte als je wist waar je voor stond.',
    clientPlaceholderNl: 'Een echt moment, geen principe.',
  },
  {
    id: 'audience',
    cat: 'Audience',
    catNl: 'Doelgroep',
    text: 'Who would be furious if this brand disappeared — and why?',
    placeholder: 'Not your target demographic. The people who actually need this.',
    textNl: 'Wie zou woedend zijn als dit merk verdween — en waarom?',
    placeholderNl: 'Niet je doelgroep. De mensen die dit echt nodig hebben.',
    clientText: 'Who would miss you most if you disappeared tomorrow — and what would they lose?',
    clientPlaceholder: 'Think beyond your best customers. Who genuinely needs what you do.',
    clientTextNl: 'Wie zou je het meest missen als je morgen verdween — en wat zouden ze kwijtraken?',
    clientPlaceholderNl: 'Denk verder dan je beste klanten. Wie heeft echt nodig wat jij doet.',
  },
  {
    id: 'ambition',
    cat: 'Ambition',
    catNl: 'Ambitie',
    text: 'What does success look like in five years? Be uncomfortably specific.',
    placeholder: 'Not revenue. What exists in the world that doesn\'t now.',
    textNl: 'Hoe ziet succes eruit over vijf jaar? Wees ongemakkelijk specifiek.',
    placeholderNl: 'Geen omzet. Wat bestaat er in de wereld dat er nu nog niet is.',
    clientText: 'Five years from now, what exists in the world because of you that doesn\'t exist today?',
    clientPlaceholder: 'Not a number. What is different.',
    clientTextNl: 'Over vijf jaar, wat bestaat er in de wereld door jou dat er vandaag nog niet is?',
    clientPlaceholderNl: 'Geen getal. Wat is er anders.',
  },
]
